### ISSUE TITLE
Update DLTx logo

### ISSUE THREAD

**Issue by bitcoinbrisbane** [dltxio/bitcoinbrisbane#33]
https://bitcoinbrisbane.sharepoint.com/sites/Social/Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2FSocial%2FShared%20Documents%2FGeneral%2FDLTx%2ELabs%20files&p=true&ga=1

**Comment by rodonguyen** [comment]
![image](https://github.com/dltxio/bitcoinbrisbane/assets/30222384/4f629603-cbc9-4009-9dd6-d65a59bc9b52)
updated on Strapi
